### ISSUE TITLE
Clear Votes button

### ISSUE THREAD

**Issue by felipedelfim** [funretro/distributed#112]

**Comment by glauberramos** [comment]
@felipedelfim could you explain why do you think this is important?

**Comment by duggym122** [comment]
@glauberramos I know this is old, but I can speak to it. To maintain consistency, and aid in following up on items we have selected to monitor and track during retro sessions, we tend to use our funretro URL as long as it is available and keep "top voted" items in a special column. We want to be able to remove votes from the board so that items can be reconsidered without having to rely on each team member to remove their vote after the retrospective session has concluded.
