### ISSUE TITLE
Improve voting system

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#122]
- Upon board creation set max votes per user
- User can see how many votes are left
- Users can vote more than once on each card
- Improve unvote button (today looks like dislike)
- See clearly which cards I voted

**Comment by Roshanjossey** [comment]
@glauberramos: I have a question regarding changing unvote button. From what I understand, we're trying to solve the problem that users might think the current button is doing something different than removing their vote. I saw the same opinion in [Uservoice](https://funretrospectives.uservoice.com/forums/269818-general/suggestions/13206210-change-unlike-button-design) too. Are we gonna implement toggling a background highlight?

**Comment by glauberramos** [comment]
My first idea was to have a "x" button to remove the vote.

Here is a screenshot: 
<img width="419" alt="screen shot 2016-12-22 at 1 35 54 pm" src="https://cloud.githubusercontent.com/assets/559434/21430754/a5d9d36a-c84b-11e6-9350-1a69dad45888.png">

**Comment by cawlin** [comment]
I think emulating "dot voting" would be a good way to go. Something like this:

![vote-mockup](https://cloud.githubusercontent.com/assets/370173/23878888/9178c1d4-080f-11e7-8d00-9f6239affd9e.gif)

* User's dots are a unique colour/symbol only to them
* All other user's dots appear the same colour
* Click to add or remove dots

The indicator for number of votes would need an obvious place to live. My gif is just to demonstrate the idea.

**Comment by Roshanjossey** [comment]
@cawlin, very interesting idea. It solves a lot of problems in one shot.

That being said, I have a lot of questions like if the UI is intuitive enough as a voting action. I think a good way to take this forward might be to prototype this very quickly and have some user interviews.

BTW, @cawlin How did you create the gif above. Are you using Funretro itself? I'm interested to learn more about it

**Comment by cawlin** [comment]
Hey @Roshanjossey 

1. I just found funretro and used it for the first time with my team last week. It worked great but we really need multi-voting to support our process!
2. I have seen this style of UI somewhere else but I forget the exact software. I can track it down though - give me a day or two.
3. The gif above is [balsamiq](https://balsamiq.com/) and then quickly animated with photoshop.

**Comment by glauberramos** [comment]
Hey @cawlin,

Thanks for the mockups, they are really great.

I like how the user can know where he voted already, also see how many votes are left.

I already have a PR open with a similar idea, with multiple votes, here is how it is looking today:

![gifvoting](https://cloud.githubusercontent.com/assets/559434/23930289/251ceece-090a-11e7-8715-097b037cc775.gif)

**Comment by cawlin** [comment]
@Roshanjossey found the dot voting UI! Seems exactly as I remembered it
https://dotstorming.com/

**Comment by cawlin** [comment]
@glauberramos oh cool - maybe I'll have to set up a local instance and try it out. Less drastic change for sure!

**Comment by mrzinger** [comment]
Maybe this solution will work?
![testuservoice](https://cloud.githubusercontent.com/assets/1550163/24065135/2b554fc8-0b69-11e7-96a6-e85856172bcd.gif)
It is very simiple in implementation and at the same time shows how your change affects total votes on the message?

**Comment by Roshanjossey** [comment]
@mrzinger: I got a little confused while understanding which number shows the votes I added vs how many votes does a card have.

Users might also have similar doubts. IMHO votes on a card should be given emphasis. Maybe make it bigger and move it to a prominent position.

**Comment by mrzinger** [comment]
Ok, I made another PoC. Here it goes below:
![votes](https://cloud.githubusercontent.com/assets/1550163/24376195/524af630-133b-11e7-9d96-93a187bcb482.gif)
**Motivation:**

- Trying to emphasize the added votes by any font changes looks a bit ugly to me since it adds inconsistency the the UI 
- Stars concept proposed above looks nice, but when it comes to simultaneous work with the same board by few people we get into troubles with defining what amount of stars we have to show at what point of time
- Considering point above the most understandable way to show users votes is the figures.
- To save space and make the interface cleaner votes number appears only on the cards that user have made a vote, so the user can distinguish which card he/she voted for
- To make it clear which figure is what the voting process (up- and down-vote click) accompanied with animation showing +1 or -1 correspondingly

It is already implemented concept so if you like it I can commit it to corresponding branch. Though I am not   web developer at all so may re-invent some bicycles.
P.S. I really want this feature in "production" :)

**Comment by glauberramos** [comment]
Hello @mrzinger,

I will incorporate the ideas from the thread into my branch. The branch is actually functional, so it will be small things to add.

I think I can finish it today.

Glauber

**Comment by glauberramos** [comment]
Hey guys,

I just deployed a version to production. I am going to close this issue, please let me know what you think and if you find any issue.

**Comment by cawlin** [comment]
I dig it @glauberramos - nice use of the dots to indicate voting for the user.
