### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#152]
It would be nice to have some emoticons on the cards, so it really makes funretro more fun :D 💃

**Comment by glauberramos** [comment]
https://github.com/OneSignal/emoji-picker

**Comment by alanjsph** [comment]
Yes, adding an emoji picker would look cool. Are anyone working on this now?

**Comment by glauberramos** [comment]
@alanjsph Nobody is working on it yet.

**Comment by pamo** [comment]
Are all unicode characters supported in the input? ⌨️
`ctrl + ⌘ + space` opens the emoji picker on mac.

**Comment by pamo** [comment]
Here's an example with 'emoji support' http://funretro.github.io/distributed/#l32mxdb

**Comment by glauberramos** [comment]
It opens on mac but it is not very intuitive. Not everybody knows about it. I think if we implement a feature that works everywhere, and it just opens a modal to select some emojis, maybe it will be a better experience and work for everyone.

**Comment by glauberramos** [comment]
Maybe we could add a link/button that triggers `ctrl + ⌘ + space` only on mac. That would be like a MVP of the feature.

**Comment by pamo** [comment]
Seems reasonable but at that point you might as well add the emoji picker 😛 . I say this because you'd be binding a combination of key events to a button and then those key events would only be supported by one operating system, so you would have to determine the user's OS and only show the button if it's Mac.
