### ISSUE TITLE
Set up automated deploy step

### ISSUE THREAD

**Issue by pamo** [funretro/distributed#85]
From what I can tell, the site is served from the gh-pages branch. 

I've noticed we've been committing the dist directory and other build artifacts to master but ideally we should only ever have to push them to gh-pages. 

We can use something like the [gh-pages](https://www.npmjs.com/package/gh-pages) npm module to keep our master (development) and gh-pages (production) branches separate. 

I have [my blog](https://likescoffee.com) as an example of how these two branches can exist. The [development branch](https://github.com/pamo/pamo.github.io/tree/development) generates what goes into a public/ directory and the contents of that directory are what you see in the [master branch](https://github.com/pamo/pamo.github.io/tree/master).

I'd be happy to take this on as a task if others find it useful.

**Comment by glauberramos** [comment]
Hey pam,

I had this conversation last week with some people in the office. I like the idea of improving it because I really dont like to commit dist files everytime.

What we can do maybe is to create a script that generates dist files and creates a new branch called gh-pages and push force it to github. This way we will always have 1 commit on gh-pages with the latest changes. What do you think?

**Comment by pamo** [comment]
That's exactly what the npm module, gh-pages does 😄  👍

**Comment by glauberramos** [comment]
Cool, in my opinion we can use it them 💃

**Comment by pamo** [comment]
@glauberramos I closed this issue because I had unintentionally deployed 🙊 . We can deploy locally or (preferrably) on Snap by taking a build and promoting it to the deploy step when it's green
https://snap-ci.com/funretro/distributed/branch/master
![Uploading Screen Shot 2016-05-01 at 15.58.09.png…]()
